Repository HanIum2024-AILawyer/SSL-BE-Server, pull requests merged in 2024-08, with the labels that each got.

#5 feat/refactor: 소송장 관련 기능 개발, 소송장 이름 분할 저장 리팩토링
  src/main/java/com/lawProject/SSL/domain/lawsuit/api/LawSuitController.java
  src/main/java/com/lawProject/SSL/domain/lawsuit/dto/FileStorageResult.java
  src/main/java/com/lawProject/SSL/domain/lawsuit/dto/lawSuitDto.java
  src/main/java/com/lawProject/SSL/domain/lawsuit/model/LawSuit.java
  src/main/java/com/lawProject/SSL/domain/lawsuit/repository/LawSuitRepository.java
  src/main/java/com/lawProject/SSL/domain/lawsuit/service/FileService.java
  src/main/java/com/lawProject/SSL/domain/lawsuit/service/LawSuitService.java
Labels: ✨ Feature, 🔨 Refactor

#6 feat: OAuth2.0 로그아웃 기능 개발
  src/main/java/com/lawProject/SSL/domain/token/model/BlacklistedToken.java
  src/main/java/com/lawProject/SSL/domain/token/repository/BlacklistedTokenRepository.java
  src/main/java/com/lawProject/SSL/domain/user/api/UserController.java
  src/main/java/com/lawProject/SSL/global/common/code/ErrorCode.java
  src/main/java/com/lawProject/SSL/global/config/SecurityConfig.java
  src/main/java/com/lawProject/SSL/global/oauth/handler/OAuthLogoutHandler.java
  src/main/java/com/lawProject/SSL/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/lawProject/SSL/global/util/JwtUtilImpl.java
Labels: ✨ Feature

#8 notification_dev
  src/main/java/com/lawProject/SSL/domain/image/model/Image.java
  src/main/java/com/lawProject/SSL/domain/inquery/api/InQueryController.java
  src/main/java/com/lawProject/SSL/domain/inquery/dao/InQueryRepository.java
  src/main/java/com/lawProject/SSL/domain/inquery/dto/InQueryDto.java
  src/main/java/com/lawProject/SSL/domain/inquery/exception/InQueryException.java
  src/main/java/com/lawProject/SSL/domain/inquery/model/InQuery.java
  src/main/java/com/lawProject/SSL/domain/inquery/model/InQueryType.java
  src/main/java/com/lawProject/SSL/domain/inquery/service/InQueryService.java
  src/main/java/com/lawProject/SSL/domain/notification/model/Notification.java
  src/main/java/com/lawProject/SSL/domain/notification/model/NotificationType.java
  src/main/java/com/lawProject/SSL/domain/user/model/User.java
  src/main/java/com/lawProject/SSL/global/common/code/ErrorCode.java
  src/main/java/com/lawProject/SSL/global/config/SecurityConfig.java
Labels: ✨ Feature

#9 api-document_refacotr
  src/main/java/com/lawProject/SSL/domain/admin/adminAPi.java
  src/main/java/com/lawProject/SSL/domain/inquery/api/InQueryController.java
  src/main/java/com/lawProject/SSL/domain/inquery/dto/InQueryDto.java
  src/main/java/com/lawProject/SSL/domain/inquery/model/InQuery.java
  src/main/java/com/lawProject/SSL/domain/inquery/service/InQueryService.java
Labels: 🐞 BugFix, ✨ Feature

#10 inquery_refactor_v2
  src/main/java/com/lawProject/SSL/domain/admin/adminAPi.java
  src/main/java/com/lawProject/SSL/domain/admin/adminApi.java
  src/main/java/com/lawProject/SSL/domain/inquery/api/InQueryController.java
  src/main/java/com/lawProject/SSL/domain/inquery/dao/InQueryRepository.java
  src/main/java/com/lawProject/SSL/domain/inquery/dto/InQueryDto.java
  src/main/java/com/lawProject/SSL/domain/inquery/service/InQueryService.java
  src/main/java/com/lawProject/SSL/global/config/SecurityConfig.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#11 lawyer_dev
  src/main/java/com/lawProject/SSL/domain/lawyer/controller/LawyerRestController.java
  src/main/java/com/lawProject/SSL/domain/lawyer/dto/LawyerDto.java
  src/main/java/com/lawProject/SSL/domain/lawyer/exception/NotEnoughStockException.java
  src/main/java/com/lawProject/SSL/domain/lawyer/model/Address.java
  src/main/java/com/lawProject/SSL/domain/lawyer/model/ContactInfo.java
  src/main/java/com/lawProject/SSL/domain/lawyer/model/Lawyer.java
  src/main/java/com/lawProject/SSL/domain/lawyer/model/LawyerTag.java
  src/main/java/com/lawProject/SSL/domain/lawyer/repository/LawyerRepository.java
  src/main/java/com/lawProject/SSL/domain/lawyer/service/LawyerService.java
Labels: 🌏 Deploy

#14 AI 서버 외부 API 연결을 통한 API 개발
  build.gradle
  src/main/java/com/lawProject/SSL/domain/chatmessage/api/ChatController.java
  src/main/java/com/lawProject/SSL/domain/chatmessage/dto/MessageDto.java
  src/main/java/com/lawProject/SSL/domain/chatmessage/model/SenderType.java
  src/main/java/com/lawProject/SSL/domain/chatroom/api/ChatRoomController.java
  src/main/java/com/lawProject/SSL/domain/chatroom/application/ChatRoomService.java
  src/main/java/com/lawProject/SSL/domain/chatroom/dto/ChatRoomDto.java
  src/main/java/com/lawProject/SSL/domain/chatroom/model/ChatRoom.java
  src/main/java/com/lawProject/SSL/domain/langchain/api/LangChainController.java
  src/main/java/com/lawProject/SSL/domain/langchain/api/OllamaApiController.java
  src/main/java/com/lawProject/SSL/domain/langchain/dao/MessageRepository.java
  src/main/java/com/lawProject/SSL/domain/langchain/domain/ChatMessage.java
  src/main/java/com/lawProject/SSL/domain/langchain/domain/SenderType.java
  src/main/java/com/lawProject/SSL/domain/langchain/dto/ChatMessageDto.java
  src/main/java/com/lawProject/SSL/domain/langchain/dto/MakeDocForm.java
  src/main/java/com/lawProject/SSL/domain/langchain/service/ChatService.java
  src/main/java/com/lawProject/SSL/domain/langchain/service/OllamaApiClient.java
  src/main/java/com/lawProject/SSL/domain/lawsuit/api/LawSuitController.java
  src/main/java/com/lawProject/SSL/domain/lawsuit/service/FileService.java
  src/main/java/com/lawProject/SSL/domain/lawsuit/service/LawSuitService.java
  src/main/java/com/lawProject/SSL/domain/user/model/User.java
  src/main/java/com/lawProject/SSL/global/common/response/ApiResponse.java
  src/main/java/com/lawProject/SSL/global/config/WebClientConfig.java
  src/main/java/com/lawProject/SSL/global/redis/PublishMessage.java
Labels: 🌏 Deploy, 🐞 BugFix, ✨ Feature, 🔨 Refactor

#15 lawyer_dev
  src/main/java/com/lawProject/SSL/domain/lawyer/controller/LawyerRestController.java
  src/main/java/com/lawProject/SSL/domain/lawyer/dto/LawyerDto.java
  src/main/java/com/lawProject/SSL/domain/lawyer/model/HashTag.java
  src/main/java/com/lawProject/SSL/domain/lawyer/model/Lawyer.java
  src/main/java/com/lawProject/SSL/domain/lawyer/repository/LawyerRepository.java
  src/main/java/com/lawProject/SSL/domain/lawyer/service/LawyerService.java
Labels: 🐞 BugFix, 🙋‍♂️ Question
